layout_spectrum: 0.7234042
color:
  saturation: 0.9044043
  brandStrength: 1
  lightness: 0.493617
  brandColors:
    - '#FFFFFF'
    - '#A36553'
    - '#023030'
    - '#9ACDFA'
    - '#539201'
  rhythmicContrast: 0.8215162
typography_spectrum: 0.6617022
name: Mono cultural Resistance
